"""Add eQSL Nickname

Revision ID: 229e1f2ce062
Revises: a69619a8fd47
Create Date: 2016-06-21 07:46:24.963938

"""

# revision identifiers, used by Alembic.
revision = '229e1f2ce062'
down_revision = 'a69619a8fd47'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('logbook', sa.Column('eqsl_qth_nickname', sa.String(length=255), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('logbook', 'eqsl_qth_nickname')
    ### end Alembic commands ###
