"""Add old logbook field

Revision ID: e072762b7964
Revises: eb8858fd3d9c
Create Date: 2016-12-22 11:38:09.835930

"""

# revision identifiers, used by Alembic.
revision = 'e072762b7964'
down_revision = 'eb8858fd3d9c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('logbook', sa.Column('old', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('logbook', 'old')
    ### end Alembic commands ###
